CREATE TABLE SENSORS (
	ID SERIAL PRIMARY KEY,
	TEMPERATURE VARCHAR(255) NOT NULL,
	HUMIDITY VARCHAR(255) NOT NULL,
	ALTITUDE VARCHAR(255) NOT NULL,
	BATTERY_VOLTAGE VARCHAR(255) NOT NULL,
	DATE_VALUE TIMESTAMP
);
