CREATE TABLE SENSOR_DATA (
	ID INT NOT NULL,
	TEMPERATURE VARCHAR(255) NOT NULL,
	HUMIDITY VARCHAR(255) NOT NULL,
	ALTITUDE VARCHAR(255) NOT NULL,
	LIGHT VARCHAR(255) NOT NULL,
	DATE_VALUE TIMESTAMP
);

CREATE TABLE PERFORMANCE (
	BATTERY_POTENTIAL VARCHAR(255) NOT NULL,
	CPU_POTENTIAL VARCHAR(255) NOT NULL,
	CPU_TEMPERATURE VARCHAR(255) NOT NULL,
	MEMORY_TOTAL VARCHAR(255) NOT NULL,
	MEMORY_USED VARCHAR(255) NOT NULL,
	DATE_VALUE TIMESTAMP
);

CREATE TABLE PUMP_DATA (
	ID INT NOT NULL,
	DATE_START TIMESTAMP,
	DATE_STOP TIMESTAMP
);

CREATE TABLE NOTIFICATION (
	NOTIFICATION VARCHAR(255) NOT NULL,
	STATUS VARCHAR(255) NOT NULL,
	DATE_VALUE TIMESTAMP
);
